name: publish on github

on:
  push:
    branches:
      - main

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14  # Adjust to the appropriate Node.js version
          registry-url: https://npm.pkg.github.com/
          scope: "@ahmedayob"

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Build
        run: npm run build

      - name: Publish to GitHub Package Registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}